@startuml
'https://plantuml.com/class-diagram

class RedisConfig{
    + redisTemplate(RedisConnectionFactory factory): RedisTemplate
}
RedisConfig <-- AdminShopController
RedisConfig <-- UserShopController

class AdminShopController{
    - {static} SHOP_STATUS: Object
    - redisTemplate: RedisTemplate
}

class UserShopController{
    - {static} SHOP_STATUS: Object
    - redisTemplate: RedisTemplate

}

@enduml